language: rust
rust:
    - stable
    - beta
    - nightly
cache: cargo
matrix:
    allow_failures:
        - rust: nightly
script:
    - cargo build --verbose --features "derive"
    - cargo test --verbose --features "derive"
